- docs/HowTo/Store-Keys-Vaults/Use-Azure.md
Fix broken link for azure key vault authentication fundamentals 
Signed-off-by: Usman Saleem <usman@usmans.info>
> Fix link for azure key vault authentication fundamentals

- docs/HowTo/Get-Started/Start-Web3Signer.md
- docs/Reference/CLI/CLI-Subcommands.md
Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
Add the Eth2 network option.
Fixes #398
> Add the Eth2 network option.

- docs/HowTo/Configure-Slashing-Protection.md
Updated slashing protection database schema note.
> slashing protection note

- docs/HowTo/Configure-Slashing-Protection.md
- docs/Reference/CLI/CLI-Subcommands.md
Signed-off-by: Byron Gravenorst <byron.gravenorst@consesnsys.net>
Add the Hikari CLI option.
Fixes #91
> Add Hikari CLI option.

- docs/Reference/Key-Configuration-Files.md
Fix Azure key vault description and example
> Fix Azure key vault description and example

- docs/HowTo/Get-Started/Build-From-Source.md
- docs/HowTo/Store-Keys-Vaults/Use-Hashicorp.md
- docs/Reference/CLI/CLI-Syntax.md
- docs/Reference/Filecoin-API-Methods.md
- mkdocs.yml
Update headers to sentence case.
Fixes #94
> Update to sentence case (#94)

- docs/Concepts/Slashing-Protection.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
* Updated `--slashing-protection-enabled` option.  
* Edited formatting of examples for consistency across doc sites.  
Fixes #98
> Update slashing proctection option

- docs/HowTo/Configure-Slashing-Protection.md
- docs/Reference/CLI/CLI-Subcommands.md
Added `--slashing-protection-pruning-at-boot-enabled` CLI option and updated example.
Fixes #100 
https://pegasys-web3signer--101.org.readthedocs.build/en/101/
> Add pruning-at-boot CLI option

- mkdocs.yml
Update discord link in the documentation. The discord channel link for web3signer has already been updated in the README in the web3signer repo.
> Update discord link

- docs/HowTo/Store-Keys-HSM/Use-USB-Armory.md
- docs/HowTo/Store-Keys-HSM/Use-YubiHSM2.md
- docs/HowTo/Store-Keys-Vaults/Use-AWS.md
- docs/HowTo/Store-Keys-Vaults/Use-Azure.md
- docs/HowTo/Store-Keys-Vaults/Use-Hashicorp.md
- docs/HowTo/Use-Signing-Keys.md
- docs/Reference/Key-Configuration-Files.md
- mkdocs.yml
Document how to use AWS secrets manager to store BLS signing keys. Add key configuration file reference, and make minor edits throughout for consistency.
fixes #112 
https://pegasys-web3signer--113.com.readthedocs.build/en/113/HowTo/Store-Keys-Vaults/Use-AWS/
https://pegasys-web3signer--113.com.readthedocs.build/en/113/Reference/Key-Configuration-Files/#aws-secrets-manager
> document using AWS secrets manager

- docs/HowTo/Store-Keys-Vaults/Use-AWS.md
- docs/HowTo/Use-Configuration-File.md
- docs/HowTo/Use-Signing-Keys.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
Document `--aws-connection-cache-size` option + add section in Use AWS Secrets Manager page.
Also make minor style/syntax edits throughout CLI reference and related pages.
fixes #115 
https://pegasys-web3signer--116.com.readthedocs.build/en/116/HowTo/Store-Keys-Vaults/Use-AWS/#cache-aws-secrets-manager-when-loading-multiple-keys
https://pegasys-web3signer--116.com.readthedocs.build/en/116/Reference/CLI/CLI-Subcommands/#aws-connection-cache-size
> Doc AWS cache option & update style

- .circleci/config.yml
- fix vale ci
- and update common
Failed CI
See sucesfull checks
> fix vale ci

- docs/Concepts/Overview.md
- docs/HowTo/Use-Signing-Keys.md
- docs/Reference/CLI/CLI-Subcommands.md
Add to documentation to bulk load keystore files
Fixes #117 
https://pegasys-web3signer--118.com.readthedocs.build/en/118/HowTo/Use-Signing-Keys/#keystore-files
https://pegasys-web3signer--118.com.readthedocs.build/en/118/Reference/CLI/CLI-Subcommands/#keystores-password-file
> Bulk load keystore files

- docs/Reference/CLI/CLI-Subcommands.md
Add ropsten, kiln, gnosis, swift, and less-swift to the supported eth2 network configurations.
fixes #121 
> Doc missing eth2 network config options

- docs/HowTo/Use-Configuration-File.md
Update the use configuration file signing key locations to match the [documented command line option](https://docs.web3signer.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#key-store-path)
> HowTo: fix `key-store-path` example

- docs/HowTo/Use-Signing-Keys.md
- docs/Reference/CLI/CLI-Subcommands.md
Document CLI options and how to bulk load keys from AWS secrets manager.
fixes #124 
> Document bulk loading AWS keys

- docs/HowTo/Monitor/Metrics.md
Added an additional "Process metrics" table to the available metrics section with the new metric and its definition.
See [#480](https://github.com/ConsenSys/web3signer/issues/480)
> Process metrics added

- docs/Tutorials/Launchpad-Keystores.md
> Fix tutorial command to use network=goerli

- docs/HowTo/Use-Signing-Keys.md
- docs/Reference/Key-Configuration-Files.md
Signed-off-by: Alexandra Tran <alexandratran@protonmail.com>
Document specifying multiple key configs in one config file.
fixes #144 
> Document multi-key config files

- docs/Reference/CLI/CLI-Subcommands.md
Signed-off-by: Alexandra Tran <alexandratran@protonmail.com>
Document `watermark-repair` subcommand usage.
fixes #143 
> Document watermark-repair subcommand

- docs/HowTo/Store-Keys-Vaults/Use-AWS.md
- docs/HowTo/Use-Signing-Keys.md
- docusaurus.config.js
> Add AWS bulk load multiple keys from same secret note

- docs/Reference/API/json-rpc.md
> feat: add eth_sign to json-rpc

- docs/Reference/CLI/subcommands.md
- docs/get-started/start-web3signer.md
- docs/how-to/store-keys-vaults/azure.md
- docs/how-to/use-signing-keys.md
Adds documentation for Eth1 azure bulk loading
https://github.com/Consensys/web3signer/issues/832
> feat: add eth1 azure bulk loading

- docs/reference/cli/subcommands.md
- project-words.txt
Updated the ETH2 supported networks page.
> Update supported networks.

- docs/reference/cli/subcommands.md
Fixes #202 
Also updated some env variables and config file examples that were referencing ETH2/eth2. instead of ETH1/eth1.
> Added --azure-response-timeout CLI option

- docs/reference/api/json-rpc.md
> EthSigner -> Web3Signer fix

- docs/reference/api/json-rpc.md
Fixes #209 
Note - I still have to test my example before this is merged.
> Added eth_signTypedData

- docs/how-to/load-keys.md
- docs/how-to/store-keys/vaults/gcp.md
- docs/reference/cli/subcommands.md
- docs/reference/key-config-file-params.md
Fixes #231 (CLI options added in an earlier PR) 
@usmansaleem - I pattern matched/made an educated guess at the key configuration file names/options so they may not be right.
> Added GCP How to

- docs/how-to/store-keys/hsm/yubihsm2.md
- docs/reference/key-config-file-params.md
- project-words.txt
> Added how to load YubiHSM and fixed key config file names

- docs/concepts/tls.md
- docs/how-to/store-keys/index.md
- docs/index.md
- docusaurus.config.js
Update meta for SEO improvements.
Fixes #252
> Update meta for SEO improvements.

- docs/reference/key-config-file-params.md
- versioned_docs/version-24.6.0/reference/key-config-file-params.md
I just changed the ending ” on some lines to match the starting quotes ".
> Match ending quotes

- .github/workflows/link-check.json
- .github/workflows/nightly.yml
Add a nightly link checker action
> Add a nightly link checker action

- docs/get-started/install-binaries.md
- versioned_docs/version-25.2.0/get-started/install-binaries.md
Update link to download releases.
Fixes: #303
> Update link to download releases.

- docs/reference/cli/subcommands.md
Document Hoodi support for Hoodi testnet.
> Document Hoodi support.

- docs/how-to/store-keys/hsm/usb-armory.md
- docs/how-to/store-keys/hsm/yubihsm2.md
- docs/how-to/store-keys/index.md
- docs/index.md
- docs/reference/key-config-file-params.md
Deprecate HW security modules
Fixes: #305
> Deprecate hw signer
